name: Deploy Docker Image

on: [push, pull_request]

jobs:
  binary:
    name: Build binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.1'

      - name: Build
        run: go build -v -o dist/stockx-gif

      - name: Create tarball
        run: |
          cd dist
          tar -cvzf stockx-gif-${{ maxtrix.os }}.tar.gz stockx-gif

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin-${{ matrix.os }}
          path: dist/stockx-gif-${{ matrix.os }}.tar.gz


  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: Fyko/stockx-gif
          tags: latest ${{ github.sha }} # important!
          dockerfiles: |
            ./Dockerfile
          build-args: |
            CREATED_AT=${{ env.datetime }}
            GITHUB_SHA=${{ github.sha }}

      - name: Publish
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}