name: Docker

on: [push, pull_request]

jobs:
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: Fyko/stockx-gif
          tags: latest ${{ github.sha }} # important!
          dockerfiles: |
            ./Dockerfile
          build-args: |
            CREATED_AT=${{ env.datetime }}
            GITHUB_SHA=${{ github.sha }}

      - name: Publish
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}